// Germany Kfz-Kennzeichen — district codes, plate categories & special types

// ── Region codes ──────────────────────────────────────────────────────────────
export interface GermanyRegion {
  code: string;
  name: string;
  active: boolean; // false = historical / expired, reissuable since 2012
}

export const GERMANY_REGIONS: GermanyRegion[] = [
  { code: "A", name: "Augsburg", active: true  },
  { code: "AA", name: "Aalen", active: true  },
  { code: "AB", name: "Aschaffenburg", active: true  },
  { code: "ABG", name: "Altenburg", active: true  },
  { code: "ABI", name: "Anhalt, Bitterfeld", active: true  },
  { code: "AC", name: "Aachen", active: true  },
  { code: "AE", name: "Auerbach", active: true  },
  { code: "AH", name: "Ahaus", active: true  },
  { code: "AIB", name: "Aibling", active: true  },
  { code: "AIC", name: "Aichach", active: true  },
  { code: "AK", name: "Altenkirchen", active: true  },
  { code: "AL", name: "Altena", active: false },
  { code: "ALF", name: "Alfeld", active: true  },
  { code: "ALS", name: "Alsfeld", active: false },
  { code: "ALZ", name: "Alzenau", active: true  },
  { code: "AM", name: "Amberg", active: true  },
  { code: "AN", name: "Ansbach", active: true  },
  { code: "ANA", name: "Annaberg", active: true  },
  { code: "ANG", name: "Angermünde", active: true  },
  { code: "ANK", name: "Anklam", active: true  },
  { code: "AP", name: "Apolda", active: true  },
  { code: "APD", name: "Apolda", active: true  },
  { code: "AR", name: "Arnsberg", active: false },
  { code: "ARN", name: "Arnstadt", active: true  },
  { code: "ART", name: "Artern", active: true  },
  { code: "AS", name: "Amberg, Sulzbach", active: true  },
  { code: "ASD", name: "Aschendorf-Hümmling", active: false },
  { code: "ASL", name: "Aschersleben", active: true  },
  { code: "ASZ", name: "Aue, Schwarzenberg", active: true  },
  { code: "AT", name: "Altentreptow", active: true  },
  { code: "AU", name: "Aue", active: true  },
  { code: "AUR", name: "Aurich", active: true  },
  { code: "AW", name: "Ahrweiler", active: true  },
  { code: "AZ", name: "Alzey", active: true  },
  { code: "AZE", name: "Anhalt-zerbst", active: true  },
  { code: "AÖ", name: "Altötting", active: true  },
  { code: "B", name: "Berlin", active: true  },
  { code: "BA", name: "Bamberg", active: true  },
  { code: "BAD", name: "Baden-baden", active: true  },
  { code: "BAR", name: "Barnim", active: true  },
  { code: "BB", name: "Böblingen", active: true  },
  { code: "BBG", name: "Bernburg", active: true  },
  { code: "BBL", name: "Brandenburgische Landesregierung", active: true  },
  { code: "BC", name: "Biberach", active: true  },
  { code: "BCH", name: "Buchen", active: true  },
  { code: "BD", name: "Bundesdienst", active: true  },
  { code: "BE", name: "Beckum", active: true  },
  { code: "BED", name: "Brand-erbisdorf", active: true  },
  { code: "BEI", name: "Beilngries", active: false },
  { code: "BEL", name: "Belzig", active: true  },
  { code: "BER", name: "Bernau", active: true  },
  { code: "BF", name: "Burgsteinfurt", active: true  },
  { code: "BGD", name: "Berchtesgaden", active: true  },
  { code: "BGL", name: "Berchtesgadener Land", active: true  },
  { code: "BH", name: "Bühl", active: true  },
  { code: "BI", name: "Bielefeld", active: true  },
  { code: "BID", name: "Biedenkopf", active: true  },
  { code: "BIN", name: "Bingen", active: true  },
  { code: "BIR", name: "Birkenfeld", active: true  },
  { code: "BIT", name: "Bitburg", active: true  },
  { code: "BIW", name: "Bischofswerda", active: true  },
  { code: "BK", name: "Backnang", active: true  },
  { code: "BKS", name: "Bernkastel", active: true  },
  { code: "BL", name: "Balingen", active: true  },
  { code: "BLB", name: "Berleburg", active: true  },
  { code: "BLK", name: "Burgenlandkreis", active: true  },
  { code: "BM", name: "Bergheim", active: true  },
  { code: "BN", name: "Bonn", active: true  },
  { code: "BNA", name: "Borna", active: true  },
  { code: "BO", name: "Bochum", active: true  },
  { code: "BOG", name: "Bogen", active: true  },
  { code: "BOH", name: "Bocholt", active: true  },
  { code: "BOR", name: "Borken", active: true  },
  { code: "BOT", name: "Bottrop", active: true  },
  { code: "BP", name: "Bundespolizei", active: true  },
  { code: "BR", name: "Bruchsal", active: false },
  { code: "BRA", name: "Brake", active: true  },
  { code: "BRB", name: "Brandenburg", active: true  },
  { code: "BRG", name: "Burg", active: true  },
  { code: "BRI", name: "Brilon", active: false },
  { code: "BRK", name: "Brückenau", active: true  },
  { code: "BRL", name: "Braunlage", active: true  },
  { code: "BRV", name: "Bremervörde", active: true  },
  { code: "BS", name: "Braunschweig", active: true  },
  { code: "BSB", name: "Bersenbrück", active: true  },
  { code: "BSK", name: "Beeskow", active: true  },
  { code: "BT", name: "Bayreuth", active: true  },
  { code: "BTF", name: "Bitterfeld", active: true  },
  { code: "BU", name: "Burgdorf", active: false },
  { code: "BUL", name: "Burglengenfeld", active: true  },
  { code: "BW", name: "Bundes-wasserstraßen- Und Schifffahrtsverwaltung", active: true  },
  { code: "BWL", name: "Baden-württembergischer Landtag", active: true  },
  { code: "BYL", name: "Bayerischer Landtag", active: true  },
  { code: "BZ", name: "Bautzen", active: true  },
  { code: "BZA", name: "Bergzabern", active: false },
  { code: "BÖ", name: "Börde", active: true  },
  { code: "BÜD", name: "Büdingen", active: true  },
  { code: "BÜR", name: "Büren", active: true  },
  { code: "BÜS", name: "Büsingen", active: true  },
  { code: "BÜZ", name: "Bützow", active: true  },
  { code: "C", name: "Chemnitz", active: true  },
  { code: "CA", name: "Calau", active: true  },
  { code: "CAS", name: "Castrop", active: true  },
  { code: "CB", name: "Cottbus", active: true  },
  { code: "CE", name: "Celle", active: true  },
  { code: "CHA", name: "Cham", active: true  },
  { code: "CLP", name: "Cloppenburg", active: true  },
  { code: "CLZ", name: "Clausthal-zellerfeld", active: true  },
  { code: "CO", name: "Coburg", active: true  },
  { code: "COC", name: "Cochem", active: true  },
  { code: "COE", name: "Coesfeld", active: true  },
  { code: "CR", name: "Crailsheim", active: true  },
  { code: "CUX", name: "Cuxhaven", active: true  },
  { code: "CW", name: "Calw", active: true  },
  { code: "D", name: "Düsseldorf", active: true  },
  { code: "DA", name: "Darmstadt", active: true  },
  { code: "DAH", name: "Dachau", active: true  },
  { code: "DAN", name: "Dannenberg", active: true  },
  { code: "DAU", name: "Daun", active: true  },
  { code: "DBR", name: "Doberan", active: true  },
  { code: "DD", name: "Dresden", active: true  },
  { code: "DE", name: "Dessau", active: true  },
  { code: "DEG", name: "Deggendorf", active: true  },
  { code: "DEL", name: "Delmenhorst", active: true  },
  { code: "DGF", name: "Dingolfing", active: true  },
  { code: "DH", name: "Diepholz", active: true  },
  { code: "DI", name: "Dieburg", active: true  },
  { code: "DIL", name: "Dillenburg", active: true  },
  { code: "DIN", name: "Dinslaken", active: true  },
  { code: "DIZ", name: "Diez", active: true  },
  { code: "DKB", name: "Dinkelsbühl", active: true  },
  { code: "DL", name: "Döbeln", active: true  },
  { code: "DLG", name: "Dillingen", active: true  },
  { code: "DM", name: "Demmin", active: true  },
  { code: "DN", name: "Düren", active: true  },
  { code: "DO", name: "Dortmund", active: true  },
  { code: "DON", name: "Donauwörth", active: true  },
  { code: "DS", name: "Donaueschingen", active: true  },
  { code: "DT", name: "Detmold", active: true  },
  { code: "DU", name: "Duisburg", active: true  },
  { code: "DUD", name: "Duderstadt", active: true  },
  { code: "DW", name: "Dippoldiswalde", active: true  },
  { code: "DZ", name: "Delitzsch", active: true  },
  { code: "DÜW", name: "Dürkheim An Der Weinstraße", active: true  },
  { code: "E", name: "Essen", active: true  },
  { code: "EA", name: "Eisenach", active: true  },
  { code: "EB", name: "Eilenburg", active: true  },
  { code: "EBE", name: "Ebersberg", active: true  },
  { code: "EBN", name: "Ebern", active: true  },
  { code: "EBS", name: "Ebermannstadt", active: true  },
  { code: "ECK", name: "Eckernförde", active: true  },
  { code: "ED", name: "Erding", active: true  },
  { code: "EE", name: "Elbe, Elster", active: true  },
  { code: "EF", name: "Erfurt", active: true  },
  { code: "EG", name: "Eggenfelden", active: true  },
  { code: "EH", name: "Eisenhüttenstadt", active: true  },
  { code: "EHI", name: "Ehingen", active: false },
  { code: "EI", name: "Eichstätt", active: true  },
  { code: "EIC", name: "Eichsfeld", active: true  },
  { code: "EIH", name: "Eichstätt", active: false },
  { code: "EIL", name: "Eisleben", active: true  },
  { code: "EIN", name: "Einbeck", active: true  },
  { code: "EIS", name: "Eisenberg", active: true  },
  { code: "EL", name: "Emsland", active: true  },
  { code: "EM", name: "Emmendingen", active: true  },
  { code: "EMD", name: "Emden", active: true  },
  { code: "EMS", name: "Ems", active: true  },
  { code: "EN", name: "Ennepe", active: true  },
  { code: "ER", name: "Erlangen", active: true  },
  { code: "ERB", name: "Erbach", active: true  },
  { code: "ERH", name: "Erlangen, Höchstadt", active: true  },
  { code: "ERK", name: "Erkelenz", active: true  },
  { code: "ERZ", name: "Erzgebirge", active: true  },
  { code: "ES", name: "Esslingen", active: true  },
  { code: "ESA", name: "Eisenach", active: false },
  { code: "ESB", name: "Eschenbach", active: true  },
  { code: "ESW", name: "Eschwege", active: true  },
  { code: "EU", name: "Euskirchen", active: true  },
  { code: "EUT", name: "Eutin", active: false },
  { code: "EW", name: "Eberswalde", active: true  },
  { code: "F", name: "Frankfurt", active: true  },
  { code: "FAL", name: "Fallingbostel", active: false },
  { code: "FB", name: "Friedberg", active: true  },
  { code: "FD", name: "Fulda", active: true  },
  { code: "FDB", name: "Friedberg", active: true  },
  { code: "FDS", name: "Freudenstadt", active: true  },
  { code: "FEU", name: "Feuchtwangen", active: true  },
  { code: "FF", name: "Frankfurt", active: true  },
  { code: "FFB", name: "Fürstenfeldbruck", active: true  },
  { code: "FG", name: "Freiberg", active: true  },
  { code: "FH", name: "Frankfurt am Main-Höchst", active: false },
  { code: "FI", name: "Finsterwalde", active: true  },
  { code: "FKB", name: "Frankenberg", active: true  },
  { code: "FL", name: "Flensburg", active: true  },
  { code: "FLÖ", name: "Flöha", active: true  },
  { code: "FN", name: "Friedrichshafen", active: true  },
  { code: "FO", name: "Forchheim", active: true  },
  { code: "FOR", name: "Forst", active: true  },
  { code: "FR", name: "Freiburg", active: true  },
  { code: "FRG", name: "Freyung, Grafenau", active: true  },
  { code: "FRI", name: "Friesland", active: true  },
  { code: "FRW", name: "Freienwalde", active: true  },
  { code: "FS", name: "Freising", active: true  },
  { code: "FT", name: "Frankenthal", active: true  },
  { code: "FTL", name: "Freital", active: true  },
  { code: "FW", name: "Fürstenwalde", active: true  },
  { code: "FZ", name: "Fritzlar", active: true  },
  { code: "FÜ", name: "Fürth", active: true  },
  { code: "FÜS", name: "Füssen", active: true  },
  { code: "G", name: "Gera", active: true  },
  { code: "GA", name: "Gardelegen", active: true  },
  { code: "GAN", name: "Gandersheim", active: true  },
  { code: "GAP", name: "Garmisch-partenkirchen", active: true  },
  { code: "GC", name: "Glauchau", active: true  },
  { code: "GD", name: "Gmünd", active: true  },
  { code: "GDB", name: "Gadebusch", active: true  },
  { code: "GE", name: "Gelsenkirchen", active: true  },
  { code: "GEL", name: "Geldern", active: true  },
  { code: "GEM", name: "Gmünden am Main", active: false },
  { code: "GEO", name: "Gerolzhofen", active: true  },
  { code: "GER", name: "Germersheim", active: true  },
  { code: "GF", name: "Gifhorn", active: true  },
  { code: "GG", name: "Groß-gerau", active: true  },
  { code: "GHA", name: "Geithain", active: true  },
  { code: "GHC", name: "Gräfenhainichen", active: true  },
  { code: "GI", name: "Gießen", active: true  },
  { code: "GK", name: "Geilenkirchen", active: true  },
  { code: "GL", name: "Gladbach", active: true  },
  { code: "GLA", name: "Gladbeck", active: true  },
  { code: "GM", name: "Gummersbach", active: true  },
  { code: "GMN", name: "Grimmen", active: true  },
  { code: "GN", name: "Gelnhausen", active: true  },
  { code: "GNT", name: "Genthin", active: true  },
  { code: "GOA", name: "Goar", active: true  },
  { code: "GOH", name: "Goarshausen", active: true  },
  { code: "GP", name: "Göppingen", active: true  },
  { code: "GR", name: "Görlitz", active: true  },
  { code: "GRA", name: "Grafenau", active: true  },
  { code: "GRH", name: "Großenhain", active: true  },
  { code: "GRI", name: "Griesbach", active: true  },
  { code: "GRM", name: "Grimma", active: true  },
  { code: "GRS", name: "Gransee", active: false },
  { code: "GRZ", name: "Greiz", active: true  },
  { code: "GS", name: "Goslar", active: true  },
  { code: "GT", name: "Gütersloh", active: true  },
  { code: "GTH", name: "Gotha", active: true  },
  { code: "GUB", name: "Guben", active: true  },
  { code: "GUN", name: "Gunzenhausen", active: true  },
  { code: "GV", name: "Grevenbroich", active: true  },
  { code: "GVM", name: "Grevesmühlen", active: true  },
  { code: "GW", name: "Greifswald", active: true  },
  { code: "GZ", name: "Günzburg", active: true  },
  { code: "GÖ", name: "Göttingen", active: true  },
  { code: "GÜ", name: "Güstrow", active: true  },
  { code: "H", name: "Hannover", active: true  },
  { code: "HA", name: "Hagen", active: true  },
  { code: "HAB", name: "Hammelburg", active: true  },
  { code: "HAL", name: "Halle", active: true  },
  { code: "HAM", name: "Hamm", active: true  },
  { code: "HAS", name: "Hassfurt", active: true  },
  { code: "HB", name: "Hansestadt Bremen", active: true  },
  { code: "HBN", name: "Hildburghausen", active: true  },
  { code: "HBS", name: "Halberstadt", active: true  },
  { code: "HC", name: "Hainichen", active: true  },
  { code: "HCH", name: "Hechingen", active: true  },
  { code: "HD", name: "Heidelberg", active: true  },
  { code: "HDH", name: "Heidenheim", active: true  },
  { code: "HDL", name: "Haldensleben", active: true  },
  { code: "HE", name: "Helmstedt", active: true  },
  { code: "HEB", name: "Hersbruck", active: true  },
  { code: "HEF", name: "Hersfeld", active: true  },
  { code: "HEI", name: "Heide", active: true  },
  { code: "HEL", name: "Hessischer Landtag", active: true  },
  { code: "HER", name: "Herne", active: true  },
  { code: "HET", name: "Hettstedt", active: true  },
  { code: "HF", name: "Herford", active: true  },
  { code: "HG", name: "Homburg", active: true  },
  { code: "HGN", name: "Hagenow", active: true  },
  { code: "HGW", name: "Hansestadt Greifswald", active: true  },
  { code: "HH", name: "Hansestadt Hamburg", active: true  },
  { code: "HHM", name: "Hohenmölsen", active: true  },
  { code: "HI", name: "Hildesheim", active: true  },
  { code: "HIG", name: "Heiligenstadt", active: true  },
  { code: "HIP", name: "Hilpoltstein", active: true  },
  { code: "HK", name: "Heidekreis", active: true  },
  { code: "HL", name: "Hansestadt Lübeck", active: true  },
  { code: "HM", name: "Hameln", active: true  },
  { code: "HMÜ", name: "Hann. Münden", active: true  },
  { code: "HN", name: "Heilbronn", active: true  },
  { code: "HO", name: "Hof", active: true  },
  { code: "HOG", name: "Hofgeismar", active: true  },
  { code: "HOH", name: "Hofheim", active: true  },
  { code: "HOL", name: "Holzminden", active: true  },
  { code: "HOM", name: "Homburg", active: true  },
  { code: "HOR", name: "Horb", active: true  },
  { code: "HOT", name: "Hohenstein", active: true  },
  { code: "HP", name: "Heppenheim", active: true  },
  { code: "HR", name: "Homberg", active: true  },
  { code: "HRO", name: "Hansestadt Rostock", active: true  },
  { code: "HS", name: "Heinsberg", active: true  },
  { code: "HSK", name: "Hochsauerlandkreis", active: true  },
  { code: "HST", name: "Hansestadt Stralsund", active: true  },
  { code: "HU", name: "Hanau", active: true  },
  { code: "HUS", name: "Husum", active: false },
  { code: "HV", name: "Havelberg", active: true  },
  { code: "HVL", name: "Havelland", active: true  },
  { code: "HW", name: "Halle", active: false },
  { code: "HWI", name: "Hansestadt Wismar", active: true  },
  { code: "HX", name: "Höxter", active: true  },
  { code: "HY", name: "Hoyerswerda", active: true  },
  { code: "HZ", name: "Harz", active: true  },
  { code: "HÖS", name: "Höchstadt", active: true  },
  { code: "HÜN", name: "Hünfeld", active: false },
  { code: "IGB", name: "Ingbert", active: true  },
  { code: "IK", name: "Ilm-kreis", active: true  },
  { code: "IL", name: "Ilmenau", active: true  },
  { code: "ILL", name: "Illertissen", active: true  },
  { code: "IN", name: "Ingolstadt", active: true  },
  { code: "IS", name: "Iserlohn", active: false },
  { code: "IZ", name: "Itzehoe", active: true  },
  { code: "J", name: "Jena", active: true  },
  { code: "JB", name: "Jüterbog", active: true  },
  { code: "JE", name: "Jessen", active: true  },
  { code: "JEV", name: "Friesland", active: false },
  { code: "JL", name: "Jerichower Land", active: true  },
  { code: "JÜL", name: "Jülich", active: true  },
  { code: "K", name: "Köln", active: true  },
  { code: "KA", name: "Karlsruhe", active: true  },
  { code: "KAR", name: "Karlstadt am Main", active: false },
  { code: "KB", name: "Korbach", active: true  },
  { code: "KC", name: "Kronach", active: true  },
  { code: "KE", name: "Kempten", active: true  },
  { code: "KEH", name: "Kelheim", active: true  },
  { code: "KEL", name: "Kehl", active: true  },
  { code: "KEM", name: "Kemnath", active: true  },
  { code: "KF", name: "Kaufbeuren", active: true  },
  { code: "KG", name: "Kissingen", active: true  },
  { code: "KH", name: "Kreuznach", active: true  },
  { code: "KI", name: "Kiel", active: true  },
  { code: "KIB", name: "Kirchheimbolanden", active: true  },
  { code: "KK", name: "Kempen, Krefeld", active: true  },
  { code: "KL", name: "Kaiserslautern", active: true  },
  { code: "KLE", name: "Kleve", active: true  },
  { code: "KLZ", name: "Klötze", active: true  },
  { code: "KM", name: "Kamenz", active: true  },
  { code: "KN", name: "Konstanz", active: true  },
  { code: "KO", name: "Koblenz", active: true  },
  { code: "KR", name: "Krefeld", active: true  },
  { code: "KRU", name: "Krumbach", active: true  },
  { code: "KS", name: "Kassel", active: true  },
  { code: "KT", name: "Kitzingen", active: true  },
  { code: "KU", name: "Kulmbach", active: true  },
  { code: "KUS", name: "Kusel", active: true  },
  { code: "KW", name: "Königs Wusterhausen", active: true  },
  { code: "KY", name: "Kyritz", active: true  },
  { code: "KYF", name: "Kyffhäuser", active: true  },
  { code: "KÖN", name: "Königshofen", active: true  },
  { code: "KÖT", name: "Köthen", active: true  },
  { code: "KÖZ", name: "Kötzting", active: true  },
  { code: "KÜN", name: "Künzelsau", active: true  },
  { code: "L", name: "Leipzig", active: true  },
  { code: "LA", name: "Landshut", active: true  },
  { code: "LAN", name: "Landau", active: true  },
  { code: "LAT", name: "Lauterbach", active: false },
  { code: "LAU", name: "Lauf", active: true  },
  { code: "LB", name: "Ludwigsburg", active: true  },
  { code: "LBS", name: "Lobenstein", active: true  },
  { code: "LBZ", name: "Lübz", active: true  },
  { code: "LC", name: "Luckau", active: true  },
  { code: "LD", name: "Landau", active: true  },
  { code: "LDK", name: "Lahn-dill-kreis", active: true  },
  { code: "LDS", name: "Landkreis Dahme-spreewald", active: true  },
  { code: "LE", name: "Bad Salzuflen", active: true  },
  { code: "LEO", name: "Leonberg", active: true  },
  { code: "LER", name: "Leer", active: true  },
  { code: "LEV", name: "Leverkusen", active: true  },
  { code: "LF", name: "Laufen", active: true  },
  { code: "LG", name: "Lüneburg", active: true  },
  { code: "LH", name: "Lüdinghausen", active: true  },
  { code: "LI", name: "Lindau", active: true  },
  { code: "LIB", name: "Liebenwerda", active: true  },
  { code: "LIF", name: "Lichtenfels", active: true  },
  { code: "LIN", name: "Lingen", active: false },
  { code: "LIP", name: "Lippe", active: true  },
  { code: "LK", name: "Lübbecke", active: true  },
  { code: "LL", name: "Landsberg Am Lech", active: true  },
  { code: "LM", name: "Limburg", active: true  },
  { code: "LN", name: "Lübben", active: true  },
  { code: "LOH", name: "Lohr am Main", active: false },
  { code: "LOS", name: "Landkreis Oder-spre", active: true  },
  { code: "LP", name: "Lippstadt", active: true  },
  { code: "LR", name: "Lahr", active: true  },
  { code: "LRO", name: "Landkreis Rostock", active: true  },
  { code: "LS", name: "Märkischer Kreis", active: false },
  { code: "LSA", name: "Land Sachsen-anhalt", active: true  },
  { code: "LSN", name: "Landtag Sachsen", active: true  },
  { code: "LSZ", name: "Langensalza", active: true  },
  { code: "LU", name: "Ludwigshafen", active: true  },
  { code: "LUK", name: "Luckenwalde", active: true  },
  { code: "LUP", name: "Ludwigslust, Parchim", active: true  },
  { code: "LWL", name: "Ludwigslust", active: true  },
  { code: "LÖ", name: "Lörrach", active: true  },
  { code: "LÖB", name: "Löbau", active: true  },
  { code: "LÜD", name: "Lüdenscheid", active: false },
  { code: "LÜN", name: "Lünen", active: true  },
  { code: "M", name: "München", active: true  },
  { code: "MA", name: "Mannheim", active: true  },
  { code: "MAB", name: "Marienberg", active: true  },
  { code: "MAI", name: "Mainburg", active: true  },
  { code: "MAK", name: "Marktredwitz", active: true  },
  { code: "MAL", name: "Mallersdorf", active: true  },
  { code: "MAR", name: "Marktheidenfeld", active: false },
  { code: "MB", name: "Miesbach", active: true  },
  { code: "MC", name: "Malchin", active: true  },
  { code: "MD", name: "Magdeburg", active: true  },
  { code: "ME", name: "Mettmann", active: true  },
  { code: "MED", name: "Meldorf", active: true  },
  { code: "MEG", name: "Melsungen", active: true  },
  { code: "MEI", name: "Meißen", active: true  },
  { code: "MEK", name: "Mittlerer Erzgebirgskreis", active: true  },
  { code: "MEL", name: "Melle", active: true  },
  { code: "MEP", name: "Meppen", active: false },
  { code: "MER", name: "Merseburg", active: true  },
  { code: "MES", name: "Hochsauerlandkreis", active: true  },
  { code: "MET", name: "Mellrichstadt", active: true  },
  { code: "MG", name: "Mönchengladbach", active: true  },
  { code: "MGH", name: "Mergentheim", active: true  },
  { code: "MGN", name: "Meiningen", active: true  },
  { code: "MH", name: "Mülheim", active: true  },
  { code: "MHL", name: "Mühlhausen", active: true  },
  { code: "MI", name: "Minden", active: true  },
  { code: "MIL", name: "Miltenberg", active: true  },
  { code: "MK", name: "Märkischer Kreis", active: true  },
  { code: "MKK", name: "Main-kinzig-kreis", active: true  },
  { code: "ML", name: "Mansfelder Land", active: true  },
  { code: "MM", name: "Memmingen", active: true  },
  { code: "MN", name: "Mindelheim", active: true  },
  { code: "MO", name: "Moers", active: true  },
  { code: "MOD", name: "Marktoberdorf", active: true  },
  { code: "MOL", name: "Märkisch-oderland", active: true  },
  { code: "MON", name: "Monschau", active: true  },
  { code: "MOS", name: "Mosbach", active: true  },
  { code: "MQ", name: "Merseburg, Querfurt", active: true  },
  { code: "MR", name: "Marburg", active: true  },
  { code: "MS", name: "Münster", active: true  },
  { code: "MSE", name: "Mecklenburgische Seenplatte", active: true  },
  { code: "MSH", name: "Mansfeld, Südharz", active: true  },
  { code: "MSP", name: "Main, Spessart", active: true  },
  { code: "MST", name: "Mecklenburg-strelitz", active: true  },
  { code: "MT", name: "Montabaur", active: false },
  { code: "MTK", name: "Main-taunus-kreis", active: true  },
  { code: "MTL", name: "Muldental", active: true  },
  { code: "MU", name: "Kreis Muenchen (seit 2026)", active: true  },
  { code: "MUC", name: "Internationale Kennung Des Münchner Flughafens", active: true  },
  { code: "MVL", name: "Mecklenburg-vorpommerscher Landtag", active: true  },
  { code: "MW", name: "Mittweida", active: true  },
  { code: "MY", name: "Mayen", active: true  },
  { code: "MYK", name: "Mayen, Koblenz", active: true  },
  { code: "MZ", name: "Mainz", active: true  },
  { code: "MZG", name: "Merzig", active: true  },
  { code: "MÜ", name: "Mühldorf", active: true  },
  { code: "MÜB", name: "Münchberg", active: true  },
  { code: "MÜL", name: "Mülheim (baden)", active: true  },
  { code: "MÜN", name: "Münsingen", active: false },
  { code: "MÜR", name: "Müritz", active: true  },
  { code: "N", name: "Nürnberg", active: true  },
  { code: "NAB", name: "Nabburg", active: true  },
  { code: "NAI", name: "Naila", active: true  },
  { code: "NAU", name: "Nauen", active: true  },
  { code: "NB", name: "Neubrandenburg", active: true  },
  { code: "ND", name: "Neuburg An Der Donau", active: true  },
  { code: "NDH", name: "Nordhausen", active: true  },
  { code: "NE", name: "Neuss", active: true  },
  { code: "NEA", name: "Neustadt An Der Aisch", active: true  },
  { code: "NEB", name: "Nebra", active: true  },
  { code: "NEC", name: "Neustadt Bei Coburg", active: true  },
  { code: "NEN", name: "Neunburg", active: true  },
  { code: "NES", name: "Neustadt An Der Saale", active: true  },
  { code: "NEU", name: "Titisee-neustadt", active: true  },
  { code: "NEW", name: "Neustadt An Der Waldnaab", active: true  },
  { code: "NF", name: "Nordfriesland", active: true  },
  { code: "NH", name: "Neuhaus", active: true  },
  { code: "NI", name: "Nienburg", active: true  },
  { code: "NIB", name: "Süd Tondern", active: false },
  { code: "NK", name: "Neunkirchen", active: true  },
  { code: "NL", name: "Niedersächsischer Landtag", active: true  },
  { code: "NM", name: "Neumarkt", active: true  },
  { code: "NMB", name: "Naumburg", active: true  },
  { code: "NMS", name: "Neumünster", active: true  },
  { code: "NOH", name: "Nordhorn", active: true  },
  { code: "NOL", name: "Niederschlesische Oberlausitz", active: true  },
  { code: "NOM", name: "Northeim", active: true  },
  { code: "NOR", name: "Norden", active: true  },
  { code: "NP", name: "Neuruppin", active: true  },
  { code: "NR", name: "Neuwied Am Rhein", active: true  },
  { code: "NRW", name: "Nordrhein-westfalen", active: true  },
  { code: "NRÜ", name: "Neustadt am Rübenberge", active: false },
  { code: "NT", name: "Nürtingen", active: true  },
  { code: "NU", name: "Neu-ulm", active: true  },
  { code: "NVP", name: "Vorpommern-Rügen", active: true  },
  { code: "NW", name: "Neustadt an der Weinstraße", active: true  },
  { code: "NWM", name: "Nordwestmecklenburg", active: true  },
  { code: "NY", name: "Görlitz", active: true  },
  { code: "NZ", name: "Mecklenburgische Seenplatte", active: true  },
  { code: "NÖ", name: "Nördlingen", active: true  },
  { code: "OA", name: "Oberallgäu", active: true  },
  { code: "OAL", name: "Ostallgäu", active: true  },
  { code: "OB", name: "Oberhausen", active: true  },
  { code: "OBB", name: "Miltenberg", active: true  },
  { code: "OBG", name: "Stendal", active: true  },
  { code: "OC", name: "Börde", active: true  },
  { code: "OCH", name: "Würzburg", active: true  },
  { code: "OD", name: "Stormarn", active: true  },
  { code: "OE", name: "Olpe", active: true  },
  { code: "OF", name: "Offenbach am Main", active: true  },
  { code: "OG", name: "Ortenaukreis", active: true  },
  { code: "OH", name: "Ostholstein", active: true  },
  { code: "OHA", name: "Göttingen", active: true  },
  { code: "OHV", name: "Oberhavel", active: true  },
  { code: "OHZ", name: "Osterholz", active: true  },
  { code: "OK", name: "Börde", active: true  },
  { code: "OL", name: "Oldenburg", active: true  },
  { code: "OLD", name: "Oldenburg in Holstein", active: false },
  { code: "OP", name: "Leverkusen", active: true  },
  { code: "OPR", name: "Ostprignitz-Ruppin", active: true  },
  { code: "OR", name: "Oranienburg", active: false },
  { code: "OS", name: "Osnabrück", active: true  },
  { code: "OSL", name: "Oberspreewald-Lausitz", active: true  },
  { code: "OTT", name: "Otterndorf", active: false },
  { code: "OTW", name: "Ottweiler", active: false },
  { code: "OVI", name: "Schwandorf", active: true  },
  { code: "OVL", name: "Vogtlandkreis", active: true  },
  { code: "OVP", name: "Vorpommern-Greifswald", active: true  },
  { code: "OZ", name: "Nordsachsen", active: true  },
  { code: "P", name: "Potsdam", active: true  },
  { code: "PA", name: "Passau", active: true  },
  { code: "PAF", name: "Pfaffenhofen an der Ilm", active: true  },
  { code: "PAN", name: "Rottal-Inn", active: true  },
  { code: "PAR", name: "Kehlheim, Neumarkt in der Oberpfalz", active: true  },
  { code: "PB", name: "Paderborn", active: true  },
  { code: "PCH", name: "Ludwigslust-Parchim", active: true  },
  { code: "PE", name: "Peine", active: true  },
  { code: "PEG", name: "Bayreuth, Forchheim, Nürnberger Land", active: true  },
  { code: "PER", name: "Perleberg", active: false },
  { code: "PF", name: "Pforzheim, Stadt, Enzkreis", active: true  },
  { code: "PI", name: "Pinneberg", active: true  },
  { code: "PIR", name: "Sächsische Schweiz-Osterzgebirge", active: true  },
  { code: "PK", name: "Pritzwalk", active: false },
  { code: "PL", name: "Vogtlandkreis", active: true  },
  { code: "PLÖ", name: "Plön", active: true  },
  { code: "PM", name: "Potsdam-Mittelmark", active: true  },
  { code: "PN", name: "Saale-Orla-Kreis", active: true  },
  { code: "PR", name: "Prignitz", active: true  },
  { code: "PRÜ", name: "Eifelkreis Bitburg-Prüm", active: true  },
  { code: "PS", name: "Pirmasens, Stadt, Südwestpfalz", active: true  },
  { code: "PW", name: "Vorpommern-Greifswald", active: true  },
  { code: "PZ", name: "Uckermark", active: true  },
  { code: "QFT", name: "Saalekreis", active: true  },
  { code: "QLB", name: "Harz", active: true  },
  { code: "R", name: "Regensburg", active: true  },
  { code: "RA", name: "Rastatt", active: true  },
  { code: "RC", name: "Vogtlandkreis", active: true  },
  { code: "RD", name: "Rendsburg-Eckernförde", active: true  },
  { code: "RDG", name: "Vorpommern-Rügen", active: true  },
  { code: "RE", name: "Recklinghausen", active: true  },
  { code: "REG", name: "Regen", active: true  },
  { code: "REH", name: "Hof, Wunsiedel im Fichtelgebirge", active: true  },
  { code: "REI", name: "Berchtesgadener Land", active: true  },
  { code: "RG", name: "Meißen", active: true  },
  { code: "RH", name: "Roth", active: true  },
  { code: "RI", name: "Schaumburg", active: true  },
  { code: "RID", name: "Kelheim", active: true  },
  { code: "RIE", name: "Meißen", active: true  },
  { code: "RL", name: "Mittelsachsen", active: true  },
  { code: "RM", name: "Mecklenburgische Seenplatte", active: true  },
  { code: "RN", name: "Havelland", active: true  },
  { code: "RO", name: "Rosenheim", active: true  },
  { code: "ROD", name: "Cham, Schwandorf", active: true  },
  { code: "ROF", name: "Hersfeld-Rotenburg", active: true  },
  { code: "ROK", name: "Donnersbergkreis", active: true  },
  { code: "ROL", name: "Kelheim, Landshut", active: true  },
  { code: "ROS", name: "Rostock, Landkreis", active: true  },
  { code: "ROT", name: "Ansbach", active: true  },
  { code: "ROW", name: "Rotenburg", active: true  },
  { code: "RP", name: "Rhein-Pfalz-Kreis", active: true  },
  { code: "RS", name: "Remscheid", active: true  },
  { code: "RSL", name: "Dessau-Roßlau", active: true  },
  { code: "RT", name: "Reutlingen", active: true  },
  { code: "RU", name: "Saalfeld-Rudolstadt", active: true  },
  { code: "RV", name: "Ravensburg", active: true  },
  { code: "RW", name: "Rottweil", active: true  },
  { code: "RY", name: "Rheydt", active: false },
  { code: "RZ", name: "Herzogtum Lauenburg", active: true  },
  { code: "RÜD", name: "Rheingau-Taunus Kreis", active: true  },
  { code: "RÜG", name: "Vorpommern-Rügen", active: true  },
  { code: "S", name: "Stuttgart", active: true  },
  { code: "SAB", name: "Trier-Saarburg", active: true  },
  { code: "SAD", name: "Schwandorf", active: true  },
  { code: "SAN", name: "Hof, Kronach, Kulmbach", active: true  },
  { code: "SAW", name: "Altmarkkreis Salzwedel", active: true  },
  { code: "SB", name: "Saarbrücken", active: true  },
  { code: "SBG", name: "Vorpommern-Greifswald", active: true  },
  { code: "SBK", name: "Salzlandkreis", active: true  },
  { code: "SC", name: "Schwabach", active: true  },
  { code: "SCZ", name: "Saale-Orla-Kreis", active: true  },
  { code: "SDH", name: "Kyffhäuserkreis", active: true  },
  { code: "SDL", name: "Stendal", active: true  },
  { code: "SDT", name: "Uckermark", active: true  },
  { code: "SE", name: "Segeberg", active: true  },
  { code: "SEB", name: "Sächsische Schweiz-Osterzgebirge", active: true  },
  { code: "SEE", name: "Märkisch-Oderland", active: true  },
  { code: "SEF", name: "Neustadt an der Aisch-Bad Windsheim", active: true  },
  { code: "SEL", name: "Wunsiedel im Fichtelgebirge", active: true  },
  { code: "SF", name: "Sonthofen", active: false },
  { code: "SFA", name: "Soltau-Fallingbostel", active: false },
  { code: "SFB", name: "Oberspreewald-Lausitz", active: true  },
  { code: "SFT", name: "Salzlandkreis", active: true  },
  { code: "SG", name: "Solingen", active: true  },
  { code: "SGH", name: "Mansfeld-Südharz", active: true  },
  { code: "SHA", name: "Schwäbisch Hall", active: true  },
  { code: "SHG", name: "Schaumburg", active: true  },
  { code: "SHK", name: "Saale-Holzland-Kreis", active: true  },
  { code: "SHL", name: "Suhl", active: true  },
  { code: "SI", name: "Siegen-Wittgenstein", active: true  },
  { code: "SIG", name: "Sigmaringen", active: true  },
  { code: "SIM", name: "Rhein-Hunsrück-Kreis", active: true  },
  { code: "SK", name: "Saalekreis", active: true  },
  { code: "SL", name: "Schleswig-Flensburg", active: true  },
  { code: "SLE", name: "Düren, Euskirchen", active: true  },
  { code: "SLF", name: "Saalfeld-Rudolstadt", active: true  },
  { code: "SLG", name: "Saulgau", active: false },
  { code: "SLK", name: "Salzlandkreis", active: true  },
  { code: "SLN", name: "Altenburger Land", active: true  },
  { code: "SLS", name: "Saarlouis", active: true  },
  { code: "SLZ", name: "Wartburgkreis", active: true  },
  { code: "SLÜ", name: "Main-Kinzig-Kreis", active: true  },
  { code: "SM", name: "Schmalkalden-Meiningen", active: true  },
  { code: "SMÜ", name: "Augsburg", active: true  },
  { code: "SN", name: "Schwerin", active: true  },
  { code: "SNH", name: "Sinsheim", active: false },
  { code: "SO", name: "Soest", active: true  },
  { code: "SOB", name: "Neuburg-Schrobenhausen", active: true  },
  { code: "SOG", name: "Weilheim-Schongau", active: true  },
  { code: "SOK", name: "Saale-Orla-Kreis", active: true  },
  { code: "SOL", name: "Soltau", active: false },
  { code: "SON", name: "Sonneberg", active: true  },
  { code: "SP", name: "Speyer", active: true  },
  { code: "SPB", name: "Spree-Neiße", active: true  },
  { code: "SPN", name: "Spree-Neiße", active: true  },
  { code: "SPR", name: "Springe", active: false },
  { code: "SR", name: "Straubing", active: true  },
  { code: "SRB", name: "Märkisch-Oderland", active: true  },
  { code: "SRO", name: "Saale-Holzland-Kreis", active: true  },
  { code: "ST", name: "Steinfurt", active: true  },
  { code: "STA", name: "Starnberg", active: true  },
  { code: "STB", name: "Ludwigslust-Parchim", active: true  },
  { code: "STD", name: "Stade", active: true  },
  { code: "STE", name: "Lichtenfels", active: true  },
  { code: "STH", name: "Schaumburg-Lippe", active: false },
  { code: "STL", name: "Erzgebirgskreis", active: true  },
  { code: "STO", name: "Stockach", active: false },
  { code: "SU", name: "Rhein-Sieg-Kreis", active: true  },
  { code: "SUL", name: "Amberg-Sulzbach", active: true  },
  { code: "SW", name: "Schweinfurt", active: true  },
  { code: "SWA", name: "Rheingau-Taunus-Kreis", active: true  },
  { code: "SY", name: "Diepholz", active: true  },
  { code: "SZ", name: "Salzgitter", active: true  },
  { code: "SZB", name: "Erzgebirgskreis", active: true  },
  { code: "SÄK", name: "Säckingen", active: false },
  { code: "SÖM", name: "Sömmerda", active: true  },
  { code: "SÜW", name: "Südliche Weinstraße", active: true  },
  { code: "TBB", name: "Main-Tauber-Kreis", active: true  },
  { code: "TDO", name: "Nordsachsen", active: true  },
  { code: "TE", name: "Steinfurt", active: true  },
  { code: "TET", name: "Rostock, Landkreis", active: true  },
  { code: "TF", name: "Teltow-Fläming", active: true  },
  { code: "TG", name: "Nordsachsen", active: true  },
  { code: "TIR", name: "Tirschenreuth", active: true  },
  { code: "TO", name: "Nordsachsen", active: true  },
  { code: "TP", name: "Uckermark", active: true  },
  { code: "TR", name: "Trier, Stadt und Trier-Saarburg", active: true  },
  { code: "TS", name: "Traunstein", active: true  },
  { code: "TT", name: "Tettnang", active: false },
  { code: "TUT", name: "Tuttlingen", active: true  },
  { code: "TÖL", name: "Bad Tölz-Wolfratshausen", active: true  },
  { code: "TÖN", name: "Eiderstedt", active: false },
  { code: "TÜ", name: "Tübingen", active: true  },
  { code: "UE", name: "Uelzen", active: true  },
  { code: "UEM", name: "Vorpommern-Greifswald", active: true  },
  { code: "UER", name: "Vorpommern-Greifswald", active: true  },
  { code: "UFF", name: "Neustadt an der Aisch-Bad Windsheim", active: true  },
  { code: "UH", name: "Unstrut-Hainich-Kreis", active: true  },
  { code: "UL", name: "Ulm, Stadt, Alb-Donaukreis", active: true  },
  { code: "UM", name: "Uckermark", active: true  },
  { code: "UN", name: "Unna", active: true  },
  { code: "USI", name: "Hochtaunuskreis", active: true  },
  { code: "V", name: "Vogtlandkreis", active: true  },
  { code: "VAI", name: "Ludwigsburg", active: true  },
  { code: "VB", name: "Vogelsbergkreis", active: true  },
  { code: "VEC", name: "Vechta", active: true  },
  { code: "VER", name: "Verden", active: true  },
  { code: "VG", name: "Vorpommern-Greifswald", active: true  },
  { code: "VIB", name: "Landshut, Mühldorf am Inn, Rottal-Inn", active: true  },
  { code: "VIE", name: "Viersen", active: true  },
  { code: "VIT", name: "Regen", active: true  },
  { code: "VK", name: "Völklingen", active: true  },
  { code: "VL", name: "Villingen", active: false },
  { code: "VOF", name: "Vilshofen", active: false },
  { code: "VOH", name: "Neustadt an der Waldnaab", active: true  },
  { code: "VR", name: "Vorpommern-Rügen", active: true  },
  { code: "VS", name: "Schwarzwald-Baar-Kreis", active: true  },
  { code: "W", name: "Wuppertal", active: true  },
  { code: "WA", name: "Waldeck-Frankenberg", active: true  },
  { code: "WAF", name: "Warendorf", active: true  },
  { code: "WAK", name: "Wartburgkreis", active: true  },
  { code: "WAN", name: "Herne", active: true  },
  { code: "WAR", name: "Warburg", active: false },
  { code: "WAT", name: "Bochum", active: true  },
  { code: "WB", name: "Wittenberg", active: true  },
  { code: "WBG", name: "Wolfsburg", active: true  },
  { code: "WBS", name: "Eichsfeld", active: true  },
  { code: "WD", name: "Wiedenbrück", active: false },
  { code: "WDA", name: "Zwickau", active: true  },
  { code: "WE", name: "Weimar", active: true  },
  { code: "WEB", name: "Oberwesterwaldkreis", active: false },
  { code: "WEG", name: "Wegscheid", active: false },
  { code: "WEL", name: "Limburg-Weilburg", active: true  },
  { code: "WEM", name: "Wesermünde", active: false },
  { code: "WEN", name: "Weiden in der Oberpfalz", active: true  },
  { code: "WER", name: "Augsburg, Dillingen an der Donau", active: true  },
  { code: "WES", name: "Wesel", active: true  },
  { code: "WF", name: "Wolfenbüttel", active: true  },
  { code: "WG", name: "Wangen im Allgäu", active: false },
  { code: "WHV", name: "Wilhelmshaven", active: true  },
  { code: "WI", name: "Wiesbaden", active: true  },
  { code: "WIL", name: "Bernkastel-Wittlich", active: true  },
  { code: "WIS", name: "Nordwestmecklenburg", active: true  },
  { code: "WIT", name: "Ennepe-Ruhr-Kreis", active: true  },
  { code: "WIZ", name: "Werra-Meißner-Kreis", active: true  },
  { code: "WK", name: "Ostprignitz-Ruppin", active: true  },
  { code: "WL", name: "Harburg)", active: true  },
  { code: "WLG", name: "Vorpommern-Greifswald", active: true  },
  { code: "WM", name: "Weilheim-Schongau", active: true  },
  { code: "WMS", name: "Börde", active: true  },
  { code: "WN", name: "Rems-Murr-Kreis", active: true  },
  { code: "WND", name: "St. Wendel", active: true  },
  { code: "WO", name: "Worms", active: true  },
  { code: "WOB", name: "Wolfsburg", active: true  },
  { code: "WOH", name: "Kassel", active: true  },
  { code: "WOL", name: "Freudenstadt, Ortenaukreis", active: true  },
  { code: "WOR", name: "Bad Tölz-Wolfratshausen, München, Starnberg", active: true  },
  { code: "WOS", name: "Freyung-Grafenau", active: true  },
  { code: "WR", name: "Harz", active: true  },
  { code: "WRN", name: "Mecklenburgische Seenplatte)", active: true  },
  { code: "WS", name: "Mühldorf am Inn, Rosenheim", active: true  },
  { code: "WSF", name: "Burgenlandkreis", active: true  },
  { code: "WST", name: "Ammerland", active: true  },
  { code: "WSW", name: "Görlitz", active: true  },
  { code: "WT", name: "Waldshut", active: true  },
  { code: "WTL", name: "Osnabrück", active: true  },
  { code: "WTM", name: "Wittmund", active: true  },
  { code: "WUG", name: "Weißenburg-Gunzenhausen", active: true  },
  { code: "WUN", name: "Wunsiedel im Fichtelgebirge", active: true  },
  { code: "WUR", name: "Leipzig", active: true  },
  { code: "WW", name: "Westerwald", active: true  },
  { code: "WZ", name: "Wetzlar", active: true  },
  { code: "WZL", name: "Börde", active: true  },
  { code: "WÜ", name: "Würzburg", active: true  },
  { code: "WÜM", name: "Cham", active: true  },
  { code: "Z", name: "Zwickau", active: true  },
  { code: "ZE", name: "Anhalt-Bitterfeld", active: true  },
  { code: "ZEL", name: "Cochem-Zell", active: true  },
  { code: "ZI", name: "Görlitz", active: true  },
  { code: "ZIG", name: "Schwalm-Eder-Kreis)", active: true  },
  { code: "ZP", name: "Erzgebirgskreis", active: true  },
  { code: "ZR", name: "Greiz", active: true  },
  { code: "ZS", name: "Zossen", active: false },
  { code: "ZW", name: "Südwestpfalz, Zweibrücken", active: true  },
  { code: "ZZ", name: "Burgenlandkreis", active: true  },
  { code: "ÖHR", name: "Hohenlohekreis", active: true  },
  { code: "ÜB", name: "Überlingen", active: false },
];

GERMANY_REGIONS.sort((a, b) => a.code.localeCompare(b.code, "de"));

// ─────────────────────────────────────────────────────────────────────────────
// PLATE CATEGORY TYPES — format examples shown per category
// ─────────────────────────────────────────────────────────────────────────────
export type GermanyCategoryId =
  | "regular"         // REGION-AB1234            (max 8 total chars incl. region)
  | "din"             // REGION-AB1234            (same, DIN black plate)
  | "transit-5day"    // REGION-123456 DD.MM.YY
  | "export"          // REGION-ABC123-A DD.MM.YY
  | "oldtimer"        // REGION-AB1234H
  | "seasonal"        // REGION-AB1234 MM/MM
  | "seasonal-h"      // REGION-AB1234H MM/MM
  | "electric"        // REGION-AB1234E
  | "transferable"    // REGION-AB1234-0  (suffix 0–9, 0H–9H, 0E–9E)
  | "red"             // REGION-XX1234    (XX = 04/05/06/07)
  | "official"        // REGION-123456    (official services & consulates)
  | "state-authority" // STATECODE-123456 (BBL-123456, THL-123456…)
  | "federal"         // BD XX-123456 / BP XA-123456 / BW XB-123456 / THW-123456
  | "diplomatic";     // 0-XX-123456A / B-XX-123456A / BN-XX-123456A

export interface GermanyCategory {
  id: GermanyCategoryId;
  label: string;
  emoji: string;
  desc: string;
  group: "standard" | "temporary" | "special" | "official";
}

export const GERMANY_CATEGORIES: GermanyCategory[] = [
  // Standard
  { id: "regular",         label: "Regular",             emoji: "🟦", desc: "Standard euroband — single-line, two-line, US, motorcycle",             group: "standard"  },
  { id: "din",             label: "Historical DIN",       emoji: "⬛", desc: "Pre-1994 black DIN plates — single-line, two-line, US format",          group: "standard"  },
  // Temporary / transfer
  { id: "transit-5day",    label: "5-Day Transit",        emoji: "🟡", desc: "Kurzzeitkennzeichen — yellow, valid up to 5 days",                      group: "temporary" },
  { id: "export",          label: "Export",               emoji: "🔴", desc: "Ausfuhrkennzeichen — red plate with expiry date for export",            group: "temporary" },
  { id: "transferable",    label: "Transferable",         emoji: "🔄", desc: "Wechselkennzeichen — one plate shared between two vehicles",            group: "temporary" },
  // Special
  { id: "oldtimer",        label: "Oldtimer (H)",         emoji: "🏛️", desc: "H-Kennzeichen — historic vehicle 30+ years old",                       group: "special"   },
  { id: "seasonal",        label: "Seasonal",             emoji: "📅", desc: "Saisonkennzeichen — valid only certain months per year",                group: "special"   },
  { id: "seasonal-h",      label: "Seasonal Oldtimer",    emoji: "🗓️", desc: "Seasonal H-Kennzeichen — seasonal historic vehicle plate",              group: "special"   },
  { id: "electric",        label: "Electric (E)",         emoji: "⚡", desc: "E-Kennzeichen — electric or hydrogen vehicle, E suffix",                group: "special"   },
  { id: "red",             label: "Red Plate",            emoji: "🔴", desc: "Rotes Kennzeichen — dealer / inspection / trade / oldtimer collector",  group: "special"   },
  { id: "official",        label: "Official / Consulate", emoji: "🏢", desc: "Official services & consulates — REGION-123456",                        group: "special"   },
  // Official
  { id: "state-authority", label: "State Authority",      emoji: "🏛️", desc: "State parliament / government vehicles (BBL, THL, NRW…)",              group: "official"  },
  { id: "federal",         label: "Federal Agencies",     emoji: "🦅", desc: "BD / BP / BW / THW — federal ministry & agency vehicles",               group: "official"  },
  { id: "diplomatic",      label: "Diplomatic",           emoji: "🌐", desc: "Diplomatic corps — 0-XX-123456A / B-XX / BN-XX format",                 group: "official"  },
];

export const CATEGORY_GROUPS: { id: GermanyCategory["group"]; label: string }[] = [
  { id: "standard",  label: "Standard" },
  { id: "temporary", label: "Temporary / Transfer" },
  { id: "special",   label: "Special" },
  { id: "official",  label: "Official" },
];

// ── Plate format (sub-type within regular / din) ──────────────────────────────
export interface GermanyPlateFormat {
  id: string;
  label: string;
  desc: string;
  group: "regular" | "din";
}

export const GERMANY_PLATE_FORMATS: GermanyPlateFormat[] = [
  { id: "single",     label: "Single-line",     desc: "520×110 mm · most common",         group: "regular" },
  { id: "double",     label: "Two-line",         desc: "280×200 mm · tight spaces",        group: "regular" },
  { id: "us",         label: "US-Style",         desc: "305×152 mm · wider import format", group: "regular" },
  { id: "moto",       label: "Motorcycle",       desc: "180×200 mm · rear-only",           group: "regular" },
  { id: "din-single", label: "Single-line DIN",  desc: "Pre-1994 black/white · single row",group: "din"     },
  { id: "din-double", label: "Two-line DIN",     desc: "Pre-1994 black/white · two rows",  group: "din"     },
  { id: "din-us",     label: "US-style DIN",     desc: "Pre-1994 black/white · US size",   group: "din"     },
];

// ── Red plate sub-types ───────────────────────────────────────────────────────
export const RED_PLATE_CODES = [
  { code: "04", label: "04 — Dealer Plate" },
  { code: "05", label: "05 — Technical Inspection" },
  { code: "06", label: "06 — Trade Plates" },
  { code: "07", label: "07 — Oldtimer Collector" },
] as const;

export type RedPlateCode = "04" | "05" | "06" | "07";

// ── Transferable plate suffixes ───────────────────────────────────────────────
export const TRANSFERABLE_SUFFIXES: string[] = [
  ...Array.from({ length: 10 }, (_, i) => String(i)),        // 0-9
  ...Array.from({ length: 10 }, (_, i) => `${i}H`),          // 0H-9H
  ...Array.from({ length: 10 }, (_, i) => `${i}E`),          // 0E-9E
];

// ── State authority codes ─────────────────────────────────────────────────────
export interface GermanyStateAuthority {
  code: string;
  name: string;
  state: string;
}

export const GERMANY_STATE_AUTHORITIES: GermanyStateAuthority[] = [
  { code: "B",   name: "Berlin Senate & Mayor's Office",                      state: "Berlin" },
  { code: "BBL", name: "Brandenburg Landtag (State Government & Parliament)", state: "Brandenburg" },
  { code: "BWL", name: "Baden-Württemberg Landtag (State Government)",        state: "Baden-Württemberg" },
  { code: "BYL", name: "Bayern Landtag (Bavaria State Government)",           state: "Bavaria" },
  { code: "HB",  name: "Bremen Senate (Hanseatic City)",                      state: "Bremen" },
  { code: "HEL", name: "Hessen Landtag (Hesse State Government)",             state: "Hesse" },
  { code: "HH",  name: "Hamburg Senate (Hanseatic City)",                     state: "Hamburg" },
  { code: "LSA", name: "Land Sachsen-Anhalt (State Government)",              state: "Saxony-Anhalt" },
  { code: "LSN", name: "Land Sachsen (Saxony State Government)",              state: "Saxony" },
  { code: "MVL", name: "Mecklenburg-Vorpommern Landtag (State Government)",   state: "Mecklenburg-Vorpommern" },
  { code: "NL",  name: "Niedersachsen Landtag (Lower Saxony Government)",     state: "Lower Saxony" },
  { code: "NRW", name: "Nordrhein-Westfalen (State Government)",              state: "NRW" },
  { code: "RPL", name: "Rheinland-Pfalz Landtag (State Government)",          state: "Rhineland-Palatinate" },
  { code: "SAL", name: "Saarland (State Government)",                         state: "Saarland" },
  { code: "SH",  name: "Schleswig-Holstein (State Government)",               state: "Schleswig-Holstein" },
  { code: "THL", name: "Thüringen Landtag (Thuringia State Government)",      state: "Thuringia" },
];

// ── Federal BD agencies (BD XX-NNNNNN) ───────────────────────────────────────
export interface GermanyFederalAgency { num: number; name: string; short: string; }
export const GERMANY_FEDERAL_BD: GermanyFederalAgency[] = [
  { num:  1, short: "Bundestag",  name: "Federal Diet (Bundestag)" },
  { num:  3, short: "Bundesrat",  name: "Federal Council (Bundesrat)" },
  { num:  4, short: "BVerfG",     name: "Federal Constitutional Court" },
  { num:  5, short: "BPräs",      name: "Office of the Federal President" },
  { num:  6, short: "BKAmt",      name: "Federal Chancellery" },
  { num:  7, short: "AA",         name: "Foreign Office" },
  { num:  8, short: "Zoll",       name: "Federal Customs Service" },
  { num:  9, short: "BMI",        name: "Federal Ministry of the Interior" },
  { num: 10, short: "BMJ",        name: "Federal Ministry of Justice & Consumer Protection" },
  { num: 11, short: "BMF",        name: "Federal Ministry of Finance" },
  { num: 12, short: "BMWK",       name: "Federal Ministry for Economic Affairs & Energy" },
  { num: 13, short: "BMDV",       name: "Federal Ministry of Transport & Digital Infrastructure" },
  { num: 14, short: "BMEL",       name: "Federal Ministry of Food & Agriculture" },
  { num: 15, short: "BMAS",       name: "Federal Ministry of Labour & Social Affairs" },
  { num: 16, short: "Zoll II",    name: "Federal Customs Service (2nd series)" },
  { num: 18, short: "BMVg",       name: "Federal Ministry of Defense" },
  { num: 19, short: "BMBF",       name: "Federal Ministry of Education & Research" },
  { num: 20, short: "BMUV",       name: "Federal Ministry for the Environment & Nuclear Safety" },
  { num: 21, short: "BMFSFJ",     name: "Federal Ministry of Family Affairs, Women & Youth" },
  { num: 22, short: "BMG",        name: "Federal Ministry of Health" },
  { num: 26, short: "BMZ",        name: "Federal Ministry of Economic Cooperation & Development" },
];

// ── Federal Police BP (BP XA-NNNNNN) — vehicle type codes ────────────────────
export interface BpVehicleType { code: number; label: string; }
export const GERMANY_BP_VEHICLE_TYPES: BpVehicleType[] = [
  { code: 10, label: "10 — Motorcycles" },
  { code: 11, label: "11 — Motorcycles" },
  { code: 12, label: "12 — Motorcycles" },
  { code: 15, label: "15 — Passenger Cars" },
  { code: 16, label: "16 — Passenger Cars" },
  { code: 17, label: "17 — Passenger Cars" },
  { code: 18, label: "18 — Passenger Cars" },
  { code: 19, label: "19 — Passenger Cars" },
  { code: 20, label: "20 — Offroad Cars" },
  { code: 21, label: "21 — Offroad Cars" },
  { code: 22, label: "22 — Offroad Cars" },
  { code: 23, label: "23 — Offroad Cars" },
  { code: 24, label: "24 — Offroad Cars" },
  { code: 25, label: "25 — Minivans" },
  { code: 26, label: "26 — Minivans" },
  { code: 27, label: "27 — Minivans" },
  { code: 28, label: "28 — Minivans" },
  { code: 29, label: "29 — Minivans" },
  { code: 30, label: "30 — Mid-sized Offroad" },
  { code: 31, label: "31 — Mid-sized Offroad" },
  { code: 32, label: "32 — Mid-sized Offroad" },
  { code: 33, label: "33 — Mid-sized Offroad" },
  { code: 34, label: "34 — Mid-sized Offroad" },
  { code: 35, label: "35 — Mid-sized Offroad" },
  { code: 36, label: "36 — Mid-sized Offroad" },
  { code: 37, label: "37 — Mid-sized Offroad" },
  { code: 38, label: "38 — Mid-sized Offroad" },
  { code: 39, label: "39 — Mid-sized Offroad" },
  { code: 40, label: "40 — Trucks & Buses" },
  { code: 41, label: "41 — Trucks & Buses" },
  { code: 42, label: "42 — Trucks & Buses" },
  { code: 43, label: "43 — Trucks & Buses" },
  { code: 44, label: "44 — Trucks & Buses" },
  { code: 45, label: "45 — Trucks & Buses" },
  { code: 46, label: "46 — Trucks & Buses" },
  { code: 47, label: "47 — Trucks & Buses" },
  { code: 48, label: "48 — Trucks & Buses" },
  { code: 49, label: "49 — Trucks & Buses" },
  { code: 50, label: "50 — Armored Vehicles" },
  { code: 51, label: "51 — Armored Vehicles" },
  { code: 52, label: "52 — Armored Vehicles" },
  { code: 53, label: "53 — Armored Vehicles" },
  { code: 54, label: "54 — Armored Vehicles" },
  { code: 55, label: "55 — Trailers" },
  { code: 56, label: "56 — Trailers" },
  { code: 57, label: "57 — Trailers" },
  { code: 58, label: "58 — Trailers" },
  { code: 59, label: "59 — Trailers" },
  { code: 60, label: "60 — Electric Vehicles" },
  { code: 61, label: "61 — Electric Vehicles" },
  { code: 62, label: "62 — Unidentified" },
];

// ── Federal Waterways BW (BW XB-NNNNNN) — branch offices ─────────────────────
export interface WaterwayBranch { num: number; name: string; city: string; }
export const GERMANY_BW_BRANCHES: WaterwayBranch[] = [
  { num: 1, name: "Branch Office North",       city: "Kiel" },
  { num: 2, name: "Branch Office North-West",  city: "Aurich" },
  { num: 3, name: "Branch Office Center",      city: "Hannover" },
  { num: 4, name: "Branch Office West",        city: "Münster" },
  { num: 5, name: "Branch Office South-West",  city: "Mainz" },
  { num: 6, name: "Branch Office South",       city: "Würzburg" },
  { num: 7, name: "Branch Office East",        city: "Magdeburg" },
];

// ── Season months ─────────────────────────────────────────────────────────────
export const MONTHS = [
  { num: "01", label: "Jan" }, { num: "02", label: "Feb" }, { num: "03", label: "Mar" },
  { num: "04", label: "Apr" }, { num: "05", label: "May" }, { num: "06", label: "Jun" },
  { num: "07", label: "Jul" }, { num: "08", label: "Aug" }, { num: "09", label: "Sep" },
  { num: "10", label: "Oct" }, { num: "11", label: "Nov" }, { num: "12", label: "Dec" },
];

// ── Plate text builder ────────────────────────────────────────────────────────
export function buildGermanyPlateText(opts: {
  category: GermanyCategoryId;
  // region-based
  regionCode?: string;
  plateSuffix?: string;    // letters+numbers combined, e.g. "AB1234"
  // transit
  date?: string;           // DD.MM.YY
  // export
  exportCheckLetter?: string;
  // seasonal
  seasonStart?: string;    // MM
  seasonEnd?: string;      // MM
  // transferable
  transferSuffix?: string; // 0–9, 0H–9H, 0E–9E
  // red
  redCode?: RedPlateCode;
  numbers?: string;        // serial digits (transit / official / red / authority)
  // state authority
  stateCode?: string;
  // federal
  federalSub?: "bd" | "bp" | "bw" | "thw";
  federalBdNum?: number | null;
  federalBpCode?: number | null;
  federalBwBranch?: number | null;
  // diplomatic
  diplomPrefix?: "0" | "B" | "BN";
  diplomCountryCode?: string;  // 10–317
  diplomSerial?: string;       // up to 6 digits
  diplomCheckLetter?: string;  // optional A–Z
}): string {
  const rc  = (opts.regionCode  ?? "").toUpperCase().trim();
  const sfx = (opts.plateSuffix ?? "").toUpperCase().trim();
  const num = (opts.numbers     ?? "").trim();

  switch (opts.category) {
    case "regular":
    case "din":
      return rc && sfx ? `${rc}-${sfx}` : rc ? `${rc}-` : "";

    case "electric":
      return rc && sfx ? `${rc}-${sfx}E` : rc ? `${rc}-` : "";

    case "oldtimer":
      return rc && sfx ? `${rc}-${sfx}H` : rc ? `${rc}-` : "";

    case "seasonal": {
      const s = opts.seasonStart && opts.seasonEnd ? ` ${opts.seasonStart}/${opts.seasonEnd}` : "";
      return rc && sfx ? `${rc}-${sfx}${s}` : rc ? `${rc}-` : "";
    }
    case "seasonal-h": {
      const s = opts.seasonStart && opts.seasonEnd ? ` ${opts.seasonStart}/${opts.seasonEnd}` : "";
      return rc && sfx ? `${rc}-${sfx}H${s}` : rc ? `${rc}-` : "";
    }
    case "transferable": {
      const t = opts.transferSuffix ? `-${opts.transferSuffix}` : "";
      return rc && sfx ? `${rc}-${sfx}${t}` : rc ? `${rc}-` : "";
    }
    case "transit-5day": {
      const d = opts.date ? ` ${opts.date}` : "";
      return rc && num ? `${rc}-${num}${d}` : rc ? `${rc}-` : "";
    }
    case "export": {
      const cl = opts.exportCheckLetter ? `-${opts.exportCheckLetter.toUpperCase()}` : "";
      const d  = opts.date ? ` ${opts.date}` : "";
      return rc && sfx ? `${rc}-${sfx}${cl}${d}` : rc ? `${rc}-` : "";
    }
    case "red": {
      const code = opts.redCode ?? "04";
      return rc && num ? `${rc}-${code}${num}` : rc ? `${rc}-${code}` : "";
    }
    case "official":
      return rc && num ? `${rc}-${num}` : rc ? `${rc}-` : "";

    case "state-authority": {
      const sc = (opts.stateCode ?? "").toUpperCase().trim();
      return sc && num ? `${sc}-${num}` : sc ? `${sc}-` : "";
    }
    case "federal": {
      const sub = opts.federalSub ?? "bd";
      if (sub === "thw") return num ? `THW-${num}` : "THW-";
      if (sub === "bd")  return opts.federalBdNum && num ? `BD ${opts.federalBdNum}-${num}` : "BD-";
      if (sub === "bp")  return opts.federalBpCode && num ? `BP ${opts.federalBpCode}-${num}` : "BP-";
      if (sub === "bw")  return opts.federalBwBranch && num ? `BW ${opts.federalBwBranch}-${num}` : "BW-";
      return "";
    }
    case "diplomatic": {
      const pre  = opts.diplomPrefix ?? "0";
      const cc   = (opts.diplomCountryCode ?? "").trim();
      const ser  = (opts.diplomSerial ?? "").trim();
      const cl   = (opts.diplomCheckLetter ?? "").toUpperCase().trim();
      return cc && ser ? `${pre}-${cc}-${ser}${cl}` : `${pre}-`;
    }
    default:
      return "";
  }
}

// ── Max suffix chars for regular/similar plates ───────────────────────────────
// Total plate text is max 8 chars; region uses 1–3, leaving 5–7 for suffix
export function maxSuffixChars(regionCode: string): number {
  return Math.max(3, 8 - (regionCode?.length ?? 0));
}

// ── Plate type labels (stored in DB) ─────────────────────────────────────────
export const PLATE_TYPE_LABELS: Record<string, string> = {
  "de-regular-single":      "Regular — Single-line (Euroband)",
  "de-regular-double":      "Regular — Two-line (Euroband)",
  "de-regular-us":          "Regular — US-Style (Euroband)",
  "de-regular-moto":        "Regular — Motorcycle (Euroband)",
  "de-din-single":          "Historical DIN — Single-line",
  "de-din-double":          "Historical DIN — Two-line",
  "de-din-us":              "Historical DIN — US-Style",
  "de-transit-5day":        "5-Day Transit (Kurzzeitkennzeichen)",
  "de-export":              "Export Plate (Ausfuhrkennzeichen)",
  "de-oldtimer":            "Oldtimer / Historic (H-Kennzeichen)",
  "de-seasonal":            "Seasonal (Saisonkennzeichen)",
  "de-seasonal-h":          "Seasonal Oldtimer (Saison-H)",
  "de-electric-single":     "Electric — Single-line (E-Kennzeichen)",
  "de-electric-double":     "Electric — Two-line (E-Kennzeichen)",
  "de-electric-us":         "Electric — US-Style (E-Kennzeichen)",
  "de-electric-moto":       "Electric — Motorcycle (E-Kennzeichen)",
  "de-electric":            "Electric Vehicle (E-Kennzeichen)",
  "de-transferable":        "Transferable (Wechselkennzeichen)",
  "de-red-04":              "Red Plate — 04 Dealer",
  "de-red-05":              "Red Plate — 05 Technical Inspection",
  "de-red-06":              "Red Plate — 06 Trade Plates",
  "de-red-07":              "Red Plate — 07 Oldtimer Collector",
  "de-official":            "Official Services / Consulate",
  "de-state-authority":     "State Authority",
  "de-federal-bd":          "Federal Agency (BD)",
  "de-federal-bp":          "Federal Police (BP)",
  "de-federal-bw":          "Federal Waterways (BW)",
  "de-federal-thw":         "Federal Relief (THW)",
  "de-diplomatic":          "Diplomatic Plate",
};
